repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    # one day in the future :D
    # - id: go-imports
    # - id: no-go-testing
    # - id: golangci-lint
    # - id: go-unit-tests
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: trailing-whitespace
    - id: end-of-file-fixer
      exclude: '.*\.csv'
    - id: check-added-large-files
    - id: detect-private-key
- repo: https://github.com/FXinnovation/fx-pre-commit-afcmf
  rev: 0.2.1
  hooks:
    - id: afcmf_commit_validation
      stages: [commit-msg]
